install: true

script: true

before_deploy:
  - openssl aes-256-cbc -K $encrypted_4db0acf32f70_key -iv $encrypted_4db0acf32f70_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key

deploy:
  provider: script
  script:
    - mkdir -p dist/css
    - cp index.html dist/ && cp -R css/ dist/css
    - ssh-keyscan $KNOWN_HOST >>~/.ssh/known_hosts
    - rsync --dry-run -az --force --delete --progress -e "ssh -p22" ./dist/ $DEPLOY
  skip_cleanup: true
  on:
    branch: feature/travis
