install: true

script: true

before_deploy:
  - openssl aes-256-cbc -K $encrypted_4db0acf32f70_key -iv $encrypted_4db0acf32f70_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
  - ssh-keyscan $KNOWN_HOST >>~/.ssh/known_hosts

deploy:
  provider: script
  script: sh ./deploy.sh
  skip_cleanup: true
  on:
    branch: feature/travis
