install: true

script: true

deploy:
  skip_cleanup: true
  provider: script
  script:
    - mkdir -p dist/css
    - cp index.html dist/ && cp -R css/ dist/css
    # - rsync -az --force --delete --progress -e "ssh -p22" ./dist/ $DEPLOY
